### ISSUE TITLE
As a user I want to login so that I can be uniquely represented

### ISSUE THREAD

**Issue by Drvanon** [GridtNetwork/gridt-client#1]
Username and Password should suffice to login in. 

The user should not be able to enter any part of the app without being represented.

**Comment by marickmanrho** [comment]
To add to Robin, The user should not be able to enter any part of the app except a description page of what the app is, terms of use, code of conduct, and privacy policy.

**Comment by Drvanon** [comment]
Within the coding stage of this phase that will be the last thing I do, there is other things that will require having been written first.
