### ISSUE TITLE
As a user I want to be able to search for movements so that I can more easily find one.

### ISSUE THREAD

**Issue by Drvanon** [GridtNetwork/gridt-client#12]

**Comment by marickmanrho** [comment]
What fields are searched? do we only search on the title of a movement, or do we also search the movements description?

**Comment by Drvanon** [comment]
We could make filter first on the names and then on the short description and then on the long description, but this would all be a server side question, unless we would like to add a button for: " search in description" as well.

**Comment by JornWild** [comment]
Can we perhaps implement a tag system? Have pre-made tags that users can select to apply to their movement, and other users can search for those tags. May also help with "nudging" users to make movements that comply with our requirements.

**Comment by Drvanon** [comment]
I would say, create a user story for it and mention it to the directors.
