### ISSUE TITLE
As a community manager I would like that pull requests to development would be tested immediately so that I can know if I need to start reviewing.

### ISSUE THREAD

**Issue by Drvanon** [GridtNetwork/gridt-client#138]
Pull requests always point to api-development in our project, but it is excluded from the CI. Usually I do not need to pay a lot of attention to branches whose tests fail, so it is really useful for me to know.

**Comment by HendrikPreuter** [comment]
This needs an update as we no longer point to api-development.

**Comment by marickmanrho** [comment]
I think this is fixed, hence I close this issue.
