### ISSUE TITLE
As a user I want to navigate between the different pages through a menu so that I don't see all information on one page

### ISSUE THREAD

**Issue by PJvanVliet** [GridtNetwork/gridt-client#17]

**Comment by Drvanon** [comment]
What pages do you mean and how do you plan on implementing this?

**Comment by marickmanrho** [comment]
I think this is fixed already. The Ionic version has a working menu. But, it probably should not display all possible pages.

**Comment by Drvanon** [comment]
Maybe we could create a settings page in which you set the menu to display all pages.
