### ISSUE TITLE
As a user I want to sort out the movements on the movement page that I'm subscribed to

### ISSUE THREAD

**Issue by Yori-O92** [GridtNetwork/gridt-client#176]

**Comment by marickmanrho** [comment]
Could you provide a more detailed description for this issue? For example some criteria for when the sorting options are sufficient.

**Comment by Yori-O92** [comment]
I will reformulate the issue based on the wireframe design. Maybe this one
even goes out entirely.

**Comment by Yori-O92** [comment]
After working on the wireframe, I think this is actually not something we want.
