### ISSUE TITLE
As a movement-creator I want to be able to specify in what interval I expect a follower to perform his task so that there is a very specific goal.

### ISSUE THREAD

**Issue by Drvanon** [GridtNetwork/gridt-client#23]
Duplicate of https://github.com/GridtNetwork/gridt-server/issues/18

**Comment by marickmanrho** [comment]
What intervals should be available? e.g. do we allow for custom intervals?

I propose to include:
Daily, 3 days, Weekly, Fortnight (2 weeks), Monthly

How many options we provide depends a lot on the UI. As long that the user is able to easily select the desired option it is fine to include as many options as possible.

**Comment by Drvanon** [comment]
That might actually be better than what I had in mind (an actual date interval), maybe I will change the model to reflect these changes.

**Comment by JornWild** [comment]
How will we measure those intervals? From previous activation and then add up 24 hours etc? Because I feel like this could become confusing in other time zones. With that in mind I feel like an actual date interval might be preferable.

**Comment by Drvanon** [comment]
@Yori-O92 has made a very nice document about how to do this. Currently daily, weekly and twice a day have been implemented. However there is room for more.
