### ISSUE TITLE
There are many console.log statements that are undescriptive.

### ISSUE THREAD

**Issue by Drvanon** [GridtNetwork/gridt-client#35]
Example [here](https://github.com/GridtNetwork/gridt-client/blob/7b5cf1a36c383f34d7f608a62e68df602b9e0afa/gridt/src/app/login/login.service.ts#L61). 

This is a problem, because it increases the difficulty in debugging. In general it is a good idea to perform some kind of logging, however it is important that these contain information that is generally useful. 

Good use can also be made of the four different types of logging that are available: log, info, warn and error.

**Comment by AndraUdrescu** [comment]
I'll remove those console.logs. There were there for debugging and to check if the code works. I usually check if the info I get is corrected then after that make a console log to test if the code runs through there

**Comment by Drvanon** [comment]
I do that too! It is quite a useful technique, but it is important to either clean it up, or leave a more descriptive log. In the backlog event this is a thing I would like to deal address.

**Comment by Drvanon** [comment]
Most of these were in the pieces of code that interacted with google firebase and have been removed with the installation of the API.
