### ISSUE TITLE
Many functions do not have a specified return/parameter type.

### ISSUE THREAD

**Issue by Drvanon** [GridtNetwork/gridt-client#38]
Part of the usefulness of typescript comes from being able to statically type all functions, so that you can be told at the compiler stage (or even in your editor) if your invocation will fail or not. However a lot of functions do not specify their return type. It would be useful to go in and specify the types.

Same goes for parameters.

**Comment by AndraUdrescu** [comment]
I did not know typescript does that. I never used return type and for now I won't until needed cause I am not 100% sure how to do that

**Comment by Drvanon** [comment]
I am planning on doing a little preparation for the whole backlog event. There I will explain how these things work. They are really quite useful!
