### ISSUE TITLE
As a user I want to be able to inspect all movements so that I can register to one.

### ISSUE THREAD

**Issue by Drvanon** [GridtNetwork/gridt-client#4]
It should show the amount of people that are in the user at that moment. 
It should be ordered by popularity.

**Comment by PJvanVliet** [comment]
All movements should include a short description and the minimum requirements for completion.

**Comment by marickmanrho** [comment]
How do we sort the movements? I propose doing so on popularity.

**Comment by Drvanon** [comment]
This is what Yori proposed as well, unless a different decision is made with chiefs, this will be implemented.
