### ISSUE TITLE
As a user, I would like to be able to logout, so that I may login using another account

### ISSUE THREAD

**Issue by Yori-O92** [GridtNetwork/gridt-client#50]
This is also very useful for quick testing and demonstrating that the network indeed works as we say it does.

**Comment by Drvanon** [comment]
Is there a specific reason you have assigned yourself here? I have been working on the logout functionality as I have been rewriting authentication. Once I am finished with that, I can hand it back to you to build the actual button?

**Comment by Yori-O92** [comment]
I believe the reason was hubris. But yes, I should be able to build a button.

**Comment by Drvanon** [comment]
With commit 4e671f3ce75ffc5f33ff17ee6c46f0adcf98f8ab there is now a sensible logout functionality on the authentication interface. You can grab the functionality by importing the `auth` service:
```typescript
import { AuthService } from "../core/auth.service";
```
Then include the service in your constructor:
```typescript
@Component()
export class YourPage {
  constructor (private auth: AuthService) {}
}
```
This way you can call auth functionality in your service:
```ts
this.auth.readyAuthentication$.subscribe( 
  showTheUserReadyModalFunction, 
  revertTheUserToLoginPageFunction
);
```
