### ISSUE TITLE
As a follower, I want to be able to see the messages of leaders that have activated their signals on my timeline.

### ISSUE THREAD

**Issue by Yori-O92** [GridtNetwork/gridt-client#53]

**Comment by Drvanon** [comment]
Where should they be visible? Should it show up below the leader, or like a text bubble?

**Comment by Yori-O92** [comment]
I would suggest to display them as a text bubble and that they pop up when
you click the bubble. Or that you have one line below the leader and that
you can click that to read all of it. Whichever you think is nicest/easiest.

**Comment by Drvanon** [comment]
I've gone with a text directly under the leader.
