### ISSUE TITLE
As a follower, I want to be able to randomly replace one leader once per interval, after having activated my signal.

### ISSUE THREAD

**Issue by Yori-O92** [GridtNetwork/gridt-client#54]
The change leader functionality should become active only for a user whose signal is active.
We want to prevent that followers can 'scroll' through all users in the movement. Therefore, the change leader functionality should be usable only once per interval.
For early stage testing (when movements are small), I think it would be better to allow a follower to change only one leader per interval: after one has been changed, the user has to wait till next interval, activate their signal and change another leader again.
In a later stage, when movements get bigger, we might want to change this so that during each interval, a follower may change all of his/her four leaders.

When there are not enough users in the movement, the change leaders functionality currently removes the leader to be exchanged, but doesn't return a new one. In this case, it would be better to not remove the leader and return an error message: 'there are no other leaders in the movement, go recruit them!' or something like that.

**Comment by Drvanon** [comment]
I just realized that the requirement of only once per interval also means that the server needs to be aware when the last swap was. This is because otherwise a user could simply go to a different device to swap some more there as well. I will create a ticket on the server and do the required work there as well. This is going to be more difficult then anticipated initially.

**Comment by Drvanon** [comment]
Right now the solution I will be going for is by storing the 'swap events' in a service and comparing the dates on these swap events with the interval. This means that simply logging in and out would allow a user to "cycle through the movement". 

A more permanent solution would be to store the swap events on the server and comparing against those. That is however outside of the scope of the current project.
