### ISSUE TITLE
It might be appropriate to split the movement and user models up into types that inherit of a base and specify for each situation.

### ISSUE THREAD

**Issue by Drvanon** [GridtNetwork/gridt-client#55]
Right now we use one model of movements for all circumstances. However when we create a movement, the movement does not have an id. In the home page, it is important to keep track of how many replacements have happened this interval, etc. This adds information to the models that is only necessary in some cases. 

It would be good to specify these cases and inherit from a base case.

**Comment by Drvanon** [comment]
Maybe you could take a look at this idea as well while implementing #63?

**Comment by marickmanrho** [comment]
Some work has been done in #81 regarding the issue of models.
