### ISSUE TITLE
The main page doesn't automatically get you to homepage when you are already logged in.

### ISSUE THREAD

**Issue by AndraUdrescu** [GridtNetwork/gridt-client#58]
Even if you are logged in, the main page still asks you to log in when you refresh. You should automatically get to the home page when you are logged in.

**Comment by Drvanon** [comment]
Good feature, is currently blocked by #50.

**Comment by Drvanon** [comment]
#50 has been resolved, so this can be adressed now. @Yori-O92, any interest?

**Comment by Yori-O92** [comment]
I'll take it!
