### ISSUE TITLE
The width of cards on the home page should match the width of the screen for small enough screens.

### ISSUE THREAD

**Issue by Drvanon** [GridtNetwork/gridt-client#60]
When there is not enough content to fill up the card, it becomes very tiny. It is good to have sensible min and max widths set for both the card and its lists.

**Comment by marickmanrho** [comment]
When is a screen small enough? Now I've used 600px.

**Comment by Drvanon** [comment]
I am not really sure, 600px sounds reasonable, but this is very much a visual design kind of question.
