### ISSUE TITLE
Upon swapping a leader, a message is returned with the newly assigned leader, but the line on the page remains blank.

### ISSUE THREAD

**Issue by Yori-O92** [GridtNetwork/gridt-client#61]
I signalled in the 'book reading movement' and switched out inactive Caspeer. Got the message 'your new leader is Diederik', but he didn't show up immediately in my timeline. Instead, a blank line was displayed. I navigated to the movements page and tried to navigate back. However, the home page did not load and a blank page was displayed. After navigating back to movements and back to home again, the home page loaded correctly with Diederik as my new book reading leader.

--> Robin's reply: That implies the movements are not properly updating after a call to swap leader.

**Comment by Yori-O92** [comment]
When this happens, the console outputs the message: 

ERROR TypeError: "date_string is undefined"
    extract_timezone home.page.ts:38
    isLeaderDone home.page.ts:111
    View_HomePage_3 HomePage.html:45
    Angular 32
    RxJS 5
    Angular 9
HomePage.html:45:22


ERROR CONTEXT 
Object { view: {…}, nodeIndex: 13, nodeDef: {…}, elDef: {…}, elView: {…} }
HomePage.html:45:22

**Comment by Yori-O92** [comment]
The error occurs when switching leaders.
It states that the date_string is undefined.
The date_string is the argument taken by the funtion extract_timezone(date_string: string).
This function is called by isLeaderDone(leader, movement)
This function is called in the HTML page.

`  isLeaderDone(leader: User, movement: Movement): boolean {
    let server_timezone: number = null;
    let last_signal: Date;

    if ( leader.last_signal ) {
      server_timezone = this.extract_timezone(leader.last_signal.time_stamp);
      last_signal = new Date(Date.parse(leader.last_signal.time_stamp));
    } else {
      console.log(leader.username)
      return false;
    }

    return this.getLastOccurence(movement.interval, server_timezone) < last_signal;
  }`

The error occurs in the server_timezone line, which implies that leader.last_signal is evaluated positively, so if that is the case, I don't understand why leader.last_signal.time_stamp would then be 'undefined' as the argument of the extract_timezone function...
Could it have something to do with the function being evaluated at a point in time where it is undefined? If so, would adding some delay somewhere resolve this? (Reloading the page always results in a correct display.)

**Comment by Drvanon** [comment]
After resetting the server this issue seems to have resolved itself. A very strange thing indeed.
