### ISSUE TITLE
As a follower I want to see profile pictures next to my leaders so that I can relate to them better.

### ISSUE THREAD

**Issue by Drvanon** [GridtNetwork/gridt-client#73]
This needs to be implemented server side, but I suggest using `<ion-avatar />` for this.

**Comment by Drvanon** [comment]
The user model should be adjusted to contain a gravatar_hash string property, which can be added to https://gravatar.com/avatar/<gravatar_hash> to obtain the user's profile picture. The server will provide this information in the leaders section of a movement, as well as the profile request.

**Comment by Drvanon** [comment]
The user model should be adjusted to contain a gravatar_hash string property, which can be added to https://gravatar.com/avatar/<gravatar_hash> to obtain the user's profile picture. The server will provide this information in the leaders section of a movement, as well as the profile request.

**Comment by marickmanrho** [comment]
Isn't this already included in the last update?

**Comment by Yori-O92** [comment]
Yes, I would say so.

**Comment by marickmanrho** [comment]
Then I'm closing this Issue
